#!/bin/sh

set -eu
set -o pipefail


cat <<'EOF' > /etc/hosts
::1                        localhost localhost.localdomain devnull devnull.example.com
127.0.0.1                  localhost localhost.localdomain devnull devnull.example.com
EOF

cat <<'EOF' > /etc/pf.internal
fe80::/10
ff02::/16
10.0.0.0/8
__IPADDR4__
__IPADDR6__
EOF

# IPv4
ifconfig -u -f cidr `route -n get -inet default | awk '/interface/ {print $2}'` inet | \
    awk 'tolower($0) ~ /inet[\ \t]+((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]))/ {if(substr($2,1,3)!=127) print $2}' | \
    head -n 1 | xargs -I % sed -e 's|__IPADDR4__|%|g' -i '' /etc/pf.internal

# IPv6
ifconfig -u -f cidr `route -n get -inet6 default | awk '/interface/ {print $2}'` inet6 | \
    awk 'tolower($0) ~ /inet6[\ \t]+(([0-9a-fA-F]{1,4}:){7,7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:)|fe80:(:[0-9a-fA-F]{0,4}){0,4}%[0-9a-zA-Z]{1,}|::(ffff(:0{1,4}){0,1}:){0,1}((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])|([0-9a-fA-F]{1,4}:){1,4}:((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]))/ {if(substr($2,1,1)!="f") print $2}' | \
    head -n 1 | xargs -I % sed -e 's|__IPADDR6__|%|g' -i '' /etc/pf.internal



ip4="`drill -a devnoip.example.com @127.0.0.1 A | awk '/^devnoip/ {print $NF}'`"

if [ "$ip4" != '' ] && [ "$ip4" != 'record' ]
then
  echo "$ip4/32" >> /etc/pf.internal
  echo "$ip4 devnoip devnoip.example.com" >> /etc/hosts
fi

ip6="`drill -a devnoip.example.com @127.0.0.1 AAAA | awk '/^devnoip/ {print $NF}'`"

if [ "$ip6" != '' ] && [ "$ip6" != 'record' ]
then
  echo "$ip6/64" >> /etc/pf.internal
  echo "$ip6 devnoip devnoip.example.com" >> /etc/hosts
fi

#cp /etc/hosts /var/spool/postfix/etc/hosts

/sbin/pfctl -t internal -T replace `cat /etc/pf.internal` >/dev/null 2>&1

exit 0
