version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      pip-minor:
        update-types: ["minor", "patch"]
      pip-major:
        update-types: ["major"]

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      npm-minor:
        update-types: ["minor", "patch"]
      npm-major:
        update-types: ["major"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      gha-minor:
        update-types: ["minor", "patch"]
      gha-major:
        update-types: ["major"]
