site_name: RootService
site_url: https://www.rootservice.org/
site_description: Wir bieten Service, Support, HowTos und andere nützliche Informationen rund um die Administration von FreeBSD und Linux basierten Servern
site_author: Markus Kohlmeyer
copyright: Copyright © 2002-2024 RootService Team
repo_name: Documentation
repo_url: https://github.com/RootService/mkdocs
edit_uri: blob/main/docs/

theme:
#    name: material
    name: null
    locale: de
    language: de
    custom_dir: theme/rootservice/templates
#    custom_dir: theme/material/templates
    static_templates:
        - 404.html
    include_search_page: false
    search_index_only: true
    icon:
#        logo: logo
        logo: material/book-open-page-variant
        repo: material/github
        paypal: rootservice/paypal
    favicon: assets/favicons
#    palette:
#        - media: "(prefers-color-scheme: dark)"
#          scheme: slate
#          primary: amber
#          accent: indigo
#          toggle:
#            icon: material/weather-sunny
#            name: Switch to light mode
#        - media: "(prefers-color-scheme: light)"
#          scheme: default
#          primary: amber
#          accent: indigo
#          toggle:
#            icon: material/weather-night
#            name: Switch to dark mode
    palette:
      - media: "(prefers-color-scheme)"
        toggle:
          icon: material/brightness-auto
          name: Switch to light mode
      - scheme: default
        media: "(prefers-color-scheme: light)"
        toggle:
          icon: material/brightness-7
          name: Switch to dark mode
        primary: 'white'
        accent: 'indigo'
      - scheme: slate
        media: "(prefers-color-scheme: dark)"
        toggle:
          icon: material/brightness-4
          name: Switch to light mode
        primary: 'black'
        accent: 'indigo'
    nav_style: dark
    font:
        text: Roboto Flex
        code: Roboto Mono
    features:
#        - announce.dismiss
        - content.action.edit
        - content.action.view
        - content.code.annotate
        - content.code.copy
        - content.tabs.link
        - content.tooltips
#        - header.autohide
#        - navigation.expand
        - navigation.footer
        - navigation.indexes
        - navigation.instant
        - navigation.instant.progress
#        - navigation.instant
#        - navigation.path
        - navigation.prune
        - navigation.sections
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.top
#        - navigation.tracking
        - search.highlight
#        - search.share
        - search.suggest
        - toc.follow
#        - toc.integrate

extra_css:
#    - assets/stylesheets/extra.css

extra:
    site_publisher: RootService Team
    site_publisher_url: https://github.com/RootService
    site_author_url: https://github.com/JoeUser78
    site_license_name: Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0) Creative-Commons Lizenz
    site_license_shortname: CC BY-NC-SA 4.0
    site_license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/
    view_url: https://raw.githubusercontent.com/RootService/mkdocs
    paypal_url: https://www.paypal.me/JoeUser
    generator: false
#    alternate:
#        - name: Deutsch
#          link: /de/
#          lang: de
#        - name: English
#          link: /en/
#          lang: en
    consent:
      title: Cookie consent
      description: >- 
        We use cookies to recognize your repeated visits and preferences, as well
        as to measure the effectiveness of our documentation and whether users
        find what they're searching for. With your consent, you're helping us to
        make our documentation better.
      actions:
        - manage
        - reject
        - accept

plugins:
#    - material/blog:
#    - material/group:
#    - material/info:
#    - material/offline:
#    - material/privacy:
#        links_attr_map:
#          target: _blank
#        links_noopener: true
    - material/search:
    - material/social:
#        cards_font: Roboto
        cards_layout_options:
          font_family: Roboto
#    - material/tags:
    - minify:
#        minify_html: true

markdown_extensions:
# Python Markdown
    - markdown.extensions.abbr:
    - markdown.extensions.admonition:
    - markdown.extensions.attr_list:
    - markdown.extensions.def_list:
    - markdown.extensions.footnotes:
    - markdown.extensions.md_in_html:
    - markdown.extensions.meta:
    - markdown.extensions.smarty:
        smart_quotes: false
    - markdown.extensions.tables:
    - markdown.extensions.toc:
        permalink: true
        permalink_title: Anchor link to this section for reference
        slugify: !!python/object/apply:pymdownx.slugs.slugify
          kwds:
            case: lower
        toc_depth: 3
# Python Markdown Extensions
#    - pymdownx.arithmatex:
#        generic: true
#        block_tag: 'pre'
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret:
    - pymdownx.critic:
#        mode: view
    - pymdownx.details:
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - pymdownx.highlight:
        use_pygments: true
        auto_title: true
        linenums: true
        linenums_style: pymdownx-inline
#        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite:
    - pymdownx.keys:
        separator: "\uff0b"
        strict: true
    - pymdownx.mark:
#    - pymdownx.smartsymbols:
    - pymdownx.snippets:
        base_path:
            - docs/.snippets
#            - LICENSE.md
#        auto_append:
#            - refs.md
        check_paths: true
    - pymdownx.superfences:
        preserve_tabs: true
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.tabbed:
        alternate_style: true
        slugify: !!python/object/apply:pymdownx.slugs.slugify
          kwds:
            case: lower
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde:
#    - pymdownx.escapeall:
#        hardbreak: true
#        nbsp: true
    - pymdownx.magiclink:
#        repo_url_shortener: true
#        repo_url_shorthand: true
#        social_url_shorthand: true
#        social_url_shortener: true
#        user: JoeUser78
#        repo: RootService
#        normalize_issue_symbols: true
#    - pymdownx.progressbar:
    - pymdownx.saneheaders:
    - pymdownx.striphtml:

nav:
    - Home: 'index.md'
    - HowTos:
        - Allgemein:
            - 'howtos/general/getting_started.md'
        - Sicherheit:
            - 'howtos/security/server_hacked.md'
        - FreeBSD:
            - 'howtos/freebsd/mfsbsd_image.md'
            - Remote Installation:
                - 'howtos/freebsd/remote_install/index.md'
                - 'howtos/freebsd/remote_install/basesystem.md'
                - 'howtos/freebsd/remote_install/baseports.md'
                - 'howtos/freebsd/remote_install/basetools.md'
            - Hosting System:
                - 'howtos/freebsd/hosting_system/index.md'
                - Sicherheit:
                    - 'howtos/freebsd/hosting_system/security/certbot.md'
                    - 'howtos/freebsd/hosting_system/security/openssh.md'
                - Nameserver:
                    - 'howtos/freebsd/hosting_system/nameserver/unbound.md'
                - Datenbanken:
                    - 'howtos/freebsd/hosting_system/databases/mysql.md'
                - Mailserver:
                    - 'howtos/freebsd/hosting_system/mailserver/dovecot.md'
                    - 'howtos/freebsd/hosting_system/mailserver/postfix.md'
                    - 'howtos/freebsd/hosting_system/mailserver/opendkim.md'
                    - 'howtos/freebsd/hosting_system/mailserver/opendmarc.md'
                    - 'howtos/freebsd/hosting_system/mailserver/spamassassin.md'
                - Webserver:
                    - 'howtos/freebsd/hosting_system/webserver/apache.md'
                    - 'howtos/freebsd/hosting_system/webserver/nginx.md'
                    - 'howtos/freebsd/hosting_system/webserver/php.md'
                    - 'howtos/freebsd/hosting_system/webserver/nodejs.md'
            - 'howtos/freebsd/certificate_authority.md'
        - Gentoo:
            - 'howtos/gentoo/remote_install.md'
            - 'howtos/gentoo/certificate_authority.md'
            - 'howtos/gentoo/hosting_system.md'
    - Projekte:
        - 'projects/rootforum_community.md'
        - 'projects/mysql_tuning_primer.md'
        - 'projects/certbot_wrapper.md'
    - About:
        - 'about/terms.md'
        - 'about/privacy.md'
    - 'about/imprint.md'
