name: CI-All

on:
  pull_request:
  push:
    branches: [main]

jobs:
  security:
    uses: ./.github/workflows/security-scan.yml

  deploy-docs:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy-docs.yml
