name: Maintenance

on:
  schedule:
    - cron: "0 3 * * 0"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install yamllint
      - run: yamllint .
