name: Maintenance

on:
  schedule:
    - cron: "0 0 * * *"   # stale issues daily
    - cron: "0 5 * * 1"   # badges weekly Monday 05:00 UTC
    - cron: "0 6 * * *"   # pages status daily 06:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: crazy-max/ghaction-github-status@v3
        with:
          pages-url: https://rootservice.github.io/MKDocs/

  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 60
          days-before-close: 14
          stale-issue-message: "This issue is stale because it has been open for 60 days with no activity."
          close-issue-message: "This issue was closed because it has been inactive for 14 days since being marked stale."

  update-badges:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: pip-${{ runner.os }}-
          retention-days: 3

      - run: |
          python -m pip install --upgrade pip
          tools/update-badges.sh --commit
      - run: git push origin HEAD:main
