name: GitHub Pages Status

on:
  schedule:
    - cron: "0 6 * * *"  # täglich um 6 Uhr
  workflow_dispatch:

jobs:
  check-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Check GitHub Pages status
        uses: crazy-max/ghaction-github-status@v3
        with:
          pages-url: https://rootservice.github.io/MKDocs/
