name: README TOC

on:
  push:
    branches: [ main ]
    paths:
      - README.md

jobs:
  toc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate TOC
        run: |
          awk '/^# /{print "## Inhalt"; exit}1' README.md > .tmp_readme && mv .tmp_readme README.md
          # Simple placeholder. Replace with your preferred TOC generator if needed.
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff --cached --quiet || git commit -m "chore: update README TOC"
          git push || echo "::warning::Push failed"
