name: README TOC

on:
  push:
    branches: [ main ]
    paths:
      - README.md
  workflow_dispatch:

jobs:
  toc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update TOC
        uses: technote-space/toc-generator@v4
        with:
          TARGET_PATHS: README.md
          FOLDING: true
