name: Security CI

on:
  workflow_run:
    workflows: ["MKDocs CI", "Lighthouse CI"]
    types: [completed]

permissions:
  contents: write
  actions: read
  pull-requests: write

env:
  name: security
  TAG_PREFIX: RootService/MKDocs
  LOG_TAIL_LINES: 500
  CHROME_PATH: /usr/bin/google-chrome

jobs:
  security:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: moderate

      - name: Comment result on PR
        uses: actions/github-script@v8
        env:
          TITLE: ${{ github.event.pull_request.title }}
        with:
          result-encoding: string
          retries: 3
          script: |
            const title = process.env.TITLE;
            const pr = context.payload.workflow_run.pull_requests[0];
            if (pr) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                body: "🛡️ Security check completed: dependency review run."
              });
            }
