name: Security CI

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

permissions:
  contents: write   # Needed for PR comments
  pull-requests: write

env:
  TAG_PREFIX: RootService/MKDocs

jobs:
  security:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    outputs:
      security_status: ${{ steps.security_summary.outputs.status }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Dependency Review
        uses: actions/dependency-review-action@v4

      - name: Security summary
        id: security_summary
        if: always()
        run: |
            echo "status=success" >> $GITHUB_OUTPUT

      - name: Comment Security result on PR
        if: ${{ github.event.workflow_run.event == 'pull_request' }}
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.workflow_run.pull_requests[0];
            if (pr) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                body: `🛡️ Security CI completed with status: **${{ steps.security_summary.outputs.status }}**`
              });
            }
