name: Stale Bot

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: "Dieses Issue ist seit 30 Tagen inaktiv und wird automatisch geschlossen, wenn keine Aktivität erfolgt."
          stale-pr-message: "Dieser PR ist seit 30 Tagen inaktiv und wird automatisch geschlossen, wenn keine Aktivität erfolgt."
          days-before-stale: 30
          days-before-close: 7
